//SPDX-License-Identifier: BSD-3-Clause-Clear
/*
 * SSDFS -- SSD-oriented File System.
 *
 * fs/ssdfs/ssdfs_constants.h - SSDFS constant declarations.
 *
 * Copyright (c) 2019-2022 Viacheslav Dubeyko <slava@dubeyko.com>
 * All rights reserved.
 *
 * Authors: Viacheslav Dubeyko <slava@dubeyko.com>
 */

#ifndef _SSDFS_CONSTANTS_H
#define _SSDFS_CONSTANTS_H

/*
 * Thread types
 */
enum {
	SSDFS_PEB_READ_THREAD,
	SSDFS_PEB_FLUSH_THREAD,
	SSDFS_PEB_THREAD_TYPE_MAX,
};

/* Flush thread possible states */
enum {
	SSDFS_FLUSH_THREAD_ERROR,
	SSDFS_FLUSH_THREAD_FREE_SPACE_ABSENT,
	SSDFS_FLUSH_THREAD_RO_STATE,
	SSDFS_FLUSH_THREAD_NEED_CREATE_LOG,
	SSDFS_FLUSH_THREAD_CHECK_STOP_CONDITION,
	SSDFS_FLUSH_THREAD_GET_CREATE_REQUEST,
	SSDFS_FLUSH_THREAD_GET_UPDATE_REQUEST,
	SSDFS_FLUSH_THREAD_PROCESS_CREATE_REQUEST,
	SSDFS_FLUSH_THREAD_PROCESS_UPDATE_REQUEST,
	SSDFS_FLUSH_THREAD_WAIT_NEXT_CREATE,
	SSDFS_FLUSH_THREAD_WAIT_NEXT_UPDATE,
	SSDFS_FLUSH_THREAD_PROCESS_INVALIDATED_EXTENT,
	SSDFS_FLUSH_THREAD_WAIT_NEXT_INVALIDATE,
	SSDFS_FLUSH_THREAD_CHECK_MIGRATION_NEED,
	SSDFS_FLUSH_THREAD_START_MIGRATION_NOW,
	SSDFS_FLUSH_THREAD_COMMIT_LOG,
	SSDFS_FLUSH_THREAD_DELEGATE_CREATE_ROLE,
	SSDFS_FLUSH_THREAD_DESTROY_PEB,
};

enum {
	SSDFS_SEG_USING_GC_THREAD,
	SSDFS_SEG_USED_GC_THREAD,
	SSDFS_SEG_PRE_DIRTY_GC_THREAD,
	SSDFS_SEG_DIRTY_GC_THREAD,
	SSDFS_GC_THREAD_TYPE_MAX,
};

enum {
	SSDFS_512B	= 512,
	SSDFS_2KB	= 2048,
	SSDFS_4KB	= 4096,
	SSDFS_8KB	= 8192,
	SSDFS_16KB	= 16384,
	SSDFS_128KB	= 131072,
	SSDFS_256KB	= 262144,
	SSDFS_512KB	= 524288,
	SSDFS_2MB	= 2097152,
	SSDFS_8MB	= 8388608,
};

enum {
	SSDFS_UNKNOWN_PAGE_TYPE,
	SSDFS_USER_DATA_PAGES,
	SSDFS_METADATA_PAGES,
	SSDFS_PAGES_TYPE_MAX
};

#define SSDFS_INVALID_CNO	U64_MAX
#define SSDFS_SECTOR_SHIFT	9
#define SSDFS_DEFAULT_TIMEOUT	(msecs_to_jiffies(120000))
#define SSDFS_NANOSECS_PER_SEC	(1000000000)
#define SSDFS_SECS_PER_HOUR	(60 * 60)
#define SSDFS_HOURS_PER_DAY	(24)
#define SSDFS_DAYS_PER_WEEK	(7)
#define SSDFS_WEEKS_PER_MONTH	(4)

#ifdef CONFIG_SSDFS_ERASE_BLOCKS_GROUP
#define SSDFS_DEFAULT_PEBS_PER_GROUP	(1 << CONFIG_SSDFS_PEB_PER_GROUP_SHIFT)
#else
#define SSDFS_DEFAULT_PEBS_PER_GROUP	1
#endif /* CONFIG_SSDFS_ERASE_BLOCKS_GROUP */

#endif /* _SSDFS_CONSTANTS_H */
